
general:
    name: ~username~/~alias.lower~
    version: 1.0
    access: public
    description: Description of the installation image.

packages:
    webapp: latest
    users: latest

config:
    core.site_name: "Image Test"


